Issue 70
ethereum/EIP-Bot pull request #87
Opened 2022-05-23 06:05 UTC by JEAlfonsoP

require CC0 waiver.

2022-05-23 06:07 UTC, MicahZoltu commented on src/modules/assertions/require_cc0.ts
> +  const copyrightRegex = /^[\s\S]*\n## Copyright\nCopyright and related rights waived via \[CC0\]\(\.\.\/LICENSE.md\)\.\n?$/g;
```suggestion
  const copyrightRegex = /^[\s\S]*\n## Copyright\n{1,2}Copyright and related rights waived via \[CC0\]\(\.\.\/LICENSE.md\)\.\n?$/g;
```
Some people put a blank line below headings.  Would be nice if we could support that style.

2022-05-23 06:07 UTC, MicahZoltu commented
CI is failing.  Please investigate and address then mention me when it is passing.

2022-05-23 07:46 UTC, JEAlfonsoP commented
@MicahZoltu done

2022-05-24 06:02 UTC, MicahZoltu commented
Looks like this branch has conflicts now that the other was merged.  You *should* be able to just click the Resolve Conflicts button in GitHub to address the issue.

2022-05-24 06:03 UTC, MicahZoltu commented
Oh, this changeset appears to include the other PR as well.  It should only include the changes relevant to this PR.

2022-05-24 06:51 UTC, JEAlfonsoP commented
Sorry, It looks like they all took the requirePullNumber() remove line in /src/main.ts
I did resolve the merge conflict. If you want a cleaner PRs I will delete these and create new ones.

2022-05-27 06:26 UTC, JEAlfonsoP commented
Fixes #70

2022-05-27 12:00 UTC, MicahZoltu requested changes
Sorry, just realized I never clicked "submit review" on this.  😖

2022-05-28 05:49 UTC, MicahZoltu commented on src/modules/assertions/require_cc0.ts
> +  if (context.payload?.pull_request?.body && !(copyrightRegex.test(context.payload?.pull_request?.body))) {
TypeScript should be smart enough to figure out that we have already handled the falsy cases, so we don't need the null coalescing operator after the `&&`.
```suggestion
  if (context.payload?.pull_request?.body && !(copyrightRegex.test(context.payload.pull_request.body))) {
```

2022-07-30 10:02 UTC, MicahZoltu commented
This is now handled by EIPW.  See my comment on #89 discussing how we should decide whether something goes into this bot or EIPW.

2022-07-30 10:02 UTC, closed without merging

2022-08-02 18:44 UTC, JEAlfonsoP commented
will you reopen this PR ?